name: release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Typst
        uses: yusancky/setup-typst@v2
        id: setup-typst
        with:
          version: 'v0.8.0'

      - name: Clone zrr1999/BoneDocument
        uses: GuillaumeFalourd/clone-github-repo-action@v2.2
        with:
          depth: 1
          branch: 'main'
          owner: 'zrr1999'
          repository: 'BoneDocument'

      - name: Compile Typst files
        run: |
          mkdir -p ~/.local/share/typst/packages/local/bone-document/
          ln -s $(pwd)/BoneDocument ~/.local/share/typst/packages/local/bone-document/0.1.0
          typst compile --font-path="~/.local/share/typst/packages/local/bone-document/0.1.0/fonts/" reports/main.typ

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: reports/main.pdf

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "复现周期进展报告——${{ env.DATE }}"
          files: reports/main.pdf
