name: install
on:
  workflow_call
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Typst
        uses: yusancky/setup-typst@v2
        id: setup-typst
        with:
          version: 'v0.8.0'

      - name: Clone BoneDocument/BoneDocument
        uses: GuillaumeFalourd/clone-github-repo-action@v2.2
        with:
          depth: 1
          branch: 'main'
          owner: 'BoneDocument'
          repository: 'BoneDocument'

      - name: Clone BoneDocument/fonts
        uses: GuillaumeFalourd/clone-github-repo-action@v2.2
        with:
          depth: 1
          branch: 'main'
          owner: 'BoneDocument'
          repository: 'fonts'

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Install Typst Packages
        run: |
          mkdir -p ~/.local/share/typst/packages/local/bone-document/
          ln -s $(pwd)/BoneDocument ~/.local/share/typst/packages/local/bone-document/0.1.0
